###
POST http://localhost:8081/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Yeray",
    "email":"yeray@email.com",
    "id_client": "620f90ece8f3b3f8ee568153",
    "passw" : "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    "rol" : "Admin"
}

###
GET http://localhost:8081/api/users/client/Ecosistema1/admin HTTP/1.1

###
POST http://localhost:8081/api/tables HTTP/1.1
Content-Type: application/json

{
    "name":"MESA 1",
    "status": false,
    "id_client": "Ecosistema1",
    "id_zone": "1",
    "id_row": "1",
    "id_column":"1",
    "comensales":"10",
    "id_user":"que exista en users"
}
###
GET http://localhost:8081/api/users/61c4c5a77d7ffe11ecbe1783 HTTP/1.1

###
GET http://localhost:8081/api/users/ HTTP/1.1


###
PUT http://localhost:8081/api/users/61c4c925185c8fb6c5838862 HTTP/1.1
Content-Type: application/json

{
    "name":"Alphonse Elric",
    "email":"fullMetal@email.com"
}

###
PUT http://localhost:8081/api/users/61c4c925185c8fb6c5838862 HTTP/1.1
Content-Type: application/json

{
    "name":"Eduard Elric"
}

###
DELETE http://localhost:8081/api/users/61c4c5a77d7ffe11ecbe1783 HTTP/1.1

###
POST http://localhost:8081/api/zones HTTP/1.1
Content-Type: application/json

{
    "id_client" : "eco2",
    "zone_name" : "terraza",
    "num_tables" : 30,
    "zone_status" : true
}

###
GET http://localhost:8081/api/zones HTTP/1.1

###
GET http://localhost:8081/api/zones/61e168915f84f0d055c3b9d7 HTTP/1.1

###
POST  http://localhost:8081/api/zones HTTP/1.1
Content-Type: application/json

{
    "id_client" : "Ecosistema1",
    "zone_name" : "prueba",
    "num_tables" : 20,
    "zone_status" : false
}

###
DELETE http://localhost:8081/api/zones/61e16a32103ef9d9322ac1af HTTP/1.1

###
GET http://localhost:8081/api/tables HTTP/1.1  

###
GET http://localhost:8081/api/users/client/Ecosistema1/inactive HTTP/1.1

### Crear zona y mesas;
POST  http://localhost:8081/api/zones HTTP/1.1
Content-Type: application/json

{
    "id_client" : "Ecosistema1",
    "zone_name" : "prueba"
}
###
POST http://localhost:8081/api/tables HTTP/1.1
Content-Type: application/json

{
    "name": "mesaPrueba",
    "id_zone": "61f2ad8dd8f20cae47bf0da8",
    "numero_mesa": "7"
}

###
GET http://localhost:8081/api/tables/zone/61f02956f0fb3f60da768907 HTTP/1.1

###
DELETE  http://localhost:8081/api/tables/zone/61f02956f0fb3f60da768907 HTTP/1.1

###
POST http://localhost:8081/api/client HTTP/1.1
Content-Type: application/json

{
    "name" : "y",
    "email" : "y",
    "passw" : "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
}

###
POST http://localhost:8081/api/users HTTP/1.1
Content-Type: application/json

{
    "name" : "yeray",
    "email" : "asd@gmail.com",
    "passw" : "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
    "id_client" : "61fc6dab557d880476f3d925",
    "rol" : "Admin"
}

###
GET http://localhost:8081/api/client/email/uncorreocualquiera HTTP/1.1

###
GET http://localhost:8081/api/client HTTP/1.1

###
DELETE http://localhost:8081/api/client/61f839f58c0a3181412c109e HTTP/1.1

###
GET http://localhost:8081/api/client/validate/uncorreocualquiera/03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4 HTTP/1.1



###
DELETE  http://localhost:8081/api/tables/zone/61f02956f0fb3f60da768907 HTTP/1.1

############################### PRUEBAS PABLO #########################
POST http://localhost:8081/api/tables HTTP/1.1
Content-Type: application/json

{
    "name":"M7",
    "status": false,
    "id_client": "61fab7718b4920d2aa2d129c",
    "id_zone": "62023cfe530ff963d9eaef22",
    "num_row": "4",
    "num_column":"5",
    "ocupada": false,
    "comensales":"10",
    "comensalesMax": 5,
    "id_user":"que exista en users"
}
###
POST http://localhost:8081/api/zones HTTP/1.1
Content-Type: application/json

{
    "id_client": "61fab7718b4920d2aa2d129c",
    "zone_name": "Zona 2" 
}

###
POST http://localhost:8081/api/user HTTP/1.1
Content-Type: application/json

{
    "name": "Federico",
    "email": "No importa",
    "passw": "1234",
    "id_client": "61fab7718b4920d2aa2d129c",
    "rol": "Admin"
}

###
DELETE http://localhost:8081/api/tables/62023d22530ff963d9eaef24 HTTP/1.1

###
GET http://localhost:8081/api/tables/zone/62023a9d530ff963d9eaeef1 HTTP/1.1

###
DELETE  ////ttp://localhost:8081/api/tables/zone/62023a9d530ff963d9eaeef1 HTTP/1.1

###
GET http://localhost:8081/api/ticket/table/62023bbc530ff963d9eaef02/sin_cobrar HTTP/1.1

###
GET http://localhost:8081/api/ticket_line/ticket/6204da1db8a6d8aa0f411ff4 HTTP/1.1








